### ISSUE TITLE
Izvođenje interfejsa sa eksternu I2C, SPI, UART komunikaciju

### ISSUE THREAD

**Issue by nemanjatr** [codeandrelax/2DSpaceMapping_B#13]
- U skladu sa specifikacijom zadatka potrebno je izvesti I2C, SPI i UART konektore sa mikrokontrolera 
- Ažurirati izgled šeme na wiki stranici tako da sadrži ove konektore
- Vremenska procjena: 2 sata

**Comment by dleg98** [comment]
Utroseno vrijeme : 2h
Težina zadatka: 5
