### ISSUE TITLE
Dodavanja Wifi modula na šemu

### ISSUE THREAD

**Issue by nemanjatr** [codeandrelax/2DSpaceMapping_B#14]
- Odabir konkretno Wifi modula
- Izbor pakovanja (SMD, THT)
- Okvirno planiranje pozicioniranja modula n PCB
- Povezivanje modula u šemu
- Ažurirati postojeću šemu tako da sadrži wifi modul
- Vremenska procjena: 2 sata

**Comment by bsav98** [comment]
Utroseno vrijeme : 3h
Težina zadatka 5
