### ISSUE TITLE
Izučavanje dobijene štampane pločice

### ISSUE THREAD

**Issue by dleg98** [codeandrelax/2DSpaceMapping_B#2]
- Za ovaj zadatak potrebno je proučiti dokumentaciju dobijene štampane pločice. Uočiti koji moduli su potrebni i na koji način povezati datu pločicu sa pločicom koji realizuje tim.
- Rezultat zadatka je izrada wiki stranice
- Vremenska procjena: 3h

**Comment by nemanjatr** [comment]
Utrošeno vrijeme: 10 sati. 
Težina zadatka: 4 (10)
