### ISSUE TITLE
Simuliranje mapiranja prostora oko vozila

### ISSUE THREAD

**Issue by bsav98** [codeandrelax/2DSpaceMapping_B#34]
- Izrada aplikacije u izabranom programskom jeziku, koja simulira rad senzora, mapiranje prostora oko vozila
- Rezultat je aplikacija u Python programskom jeziku koja simulira senzor i mapiranje prostora, te dokumentacija koda na wiki stranici.
- Procjena vremena: 10 sati

**Comment by nemanjatr** [comment]
- Na repozitorijum projekta (software/2D_mappin_simulation) dodana aplikacija koja predstavlja simulacija mapiranja prostora oko vozila/senzora.
- Na wiki dodana stranica koja dokumentuje aplikaciju (04 - Izrada software-a/Simulacija rada senzora i mapiranje prostora oko vozila)
- Utrošeno vrijeme: 12 sati
- Težina zadatka 6(10)
