### ISSUE TITLE
Testiranje pokretanja servo motora za senzor

### ISSUE THREAD

**Issue by nemanjatr** [codeandrelax/2DSpaceMapping_B#42]
- Potrebno je iskoristiti jedan PWM modul mikrokontrolera za generisanje signala koji će pokretati servo motor na kojem je pričvršćen senzor za mjerenje udaljenosti.
- Istražiti način korištenja PWM-a za pokretanje konktretnog servo motora.
- Rezultat rada je kod koji se spušta na mikrokontroler i izvršava pokretanje motora, te wiki stranica na kojoj je dokumentovan rad. 
- Procjena vremena: 8 sati

**Comment by bsav98** [comment]
Utroseno vrijeme : 16 h
Težina zadatka : 7
